// Copyright 2026 Matt Hall, Equinor // MIT license
$('.collapse').collapse();
const labelButton = document.getElementById('labelButton');
const canvas = document.getElementById('canvas');
const ctx = canvas.getContext('2d');
const labelOptions = document.getElementsByName('labelOption');
const modelDropdown = document.getElementById('modelDropdown');
const freeInput = document.getElementById('freeInput');
const imageFrame = document.getElementById('imageFrame');
const placeholderText = document.getElementById('placeholderText');
const popoverContainer = document.getElementById('popoverContainer');
let image = new Image();
let originalImageSrc = null; // Store the original image source
const uploadImageLink = document.getElementById('uploadImageLink');

// Image upload click.
uploadImageLink.addEventListener('click', (event) => {
    event.preventDefault(); // Stop the link from navigating

    const fileInput = document.createElement('input');
    fileInput.type = 'file';
    fileInput.accept = 'image/*';
    fileInput.onchange = (e) => {
        loadImageFromFile(e.target.files[0]);
    };
    fileInput.click();
});

// Initialize C2PA stuff.
let c2paSdk;
let generateVerifyUrl;
let getManifestSummaryStore;

document.addEventListener('DOMContentLoaded', async () => {
  const version = '0.30.9';
  const c2paLibraryUrl = `https://cdn.jsdelivr.net/npm/c2pa@${version}/+esm`;
  const c2paWcLibraryUrl = `https://cdn.jsdelivr.net/npm/c2pa-wc/+esm`;

  try {
    // Import createC2pa and generateVerifyUrl from the c2pa library
    const c2paModule = await import(c2paLibraryUrl);
    generateVerifyUrl = c2paModule.generateVerifyUrl;

    // Import getManifestSummaryStore from the c2pa-wc library
    const c2paWcModule = await import(c2paWcLibraryUrl);
    getManifestSummaryStore = c2paWcModule.getManifestSummaryStore;

    // Initialize c2paSdk
    c2paSdk = await c2paModule.createC2pa({
      wasmSrc: `https://cdn.jsdelivr.net/npm/c2pa@${version}/dist/assets/wasm/toolkit_bg.wasm`,
      workerSrc: `https://cdn.jsdelivr.net/npm/c2pa@${version}/dist/c2pa.worker.min.js`,
    });
    console.log('C2PA SDK initialized successfully.');

  } catch (err) {
    console.error('Error initializing C2PA SDK or importing libraries:', err);
  }
});

// Enable the model dropdown only when "Choose a model" is selected.
labelOptions.forEach(option => {
  option.addEventListener('change', () => {
    modelDropdown.disabled = option.value !== 'model';
  });
});

// Copy image to clipboard function.
async function copyCanvasImageToClipboard(canvasElement) {
  try {
    // 1. Get the image data as a Blob from the canvas
    const blob = await new Promise(resolve => canvasElement.toBlob(resolve, 'image/png'));

    // 2. Create a ClipboardItem with the image Blob
    const clipboardItem = new ClipboardItem({
      [blob.type]: blob
    });

    // 3. Write the ClipboardItem to the clipboard
    await navigator.clipboard.write([clipboardItem]);

    console.log('Image copied to clipboard!');
    showToast('Copied to clipboard');
  } catch (err) {
    console.error('Failed to copy image:', err);
  }
}

// Label It button.
labelButton.addEventListener('click', () => {
const selectedOption = Array.from(labelOptions).find(option => option.checked).value;
const fontSize = canvas.width / 30;

if (selectedOption === 'ai-label') {
  // Overlay the ai-label.org banner in the bottom-right once it loads.
  const overlayImage = new Image();
  const w = canvas.width / 8;
  const h = w / 2.617;
  overlayImage.crossOrigin = "anonymous";
  overlayImage.src = "https://raw.githubusercontent.com/ecogex/ai-label/refs/heads/main/image-pack/ai-label_banner-made-with-ai.svg";
  overlayImage.onload = () => {
    ctx.drawImage(image, 0, 0);
    ctx.drawImage(overlayImage, canvas.width - w - fontSize, canvas.height - h - fontSize, w, h);
  };
} else {
  // Draw a text label in the bottom-left corner.
  const labels = {
    generated: "🔺 Generated by AI",
    model: `🔺 Generated by ${modelDropdown.value}`,
    free: freeInput.value,
  };
  const label = labels[selectedOption];
  ctx.drawImage(image, 0, 0);
  ctx.font = `${fontSize}px Arial`;
  ctx.fillStyle = 'white';
  ctx.strokeStyle = 'black';
  ctx.lineWidth = 2;
  ctx.strokeText(label, fontSize, canvas.height - fontSize);
  ctx.fillText(label, fontSize, canvas.height - fontSize);
}

// Steganography.
const secretText = document.getElementById('hiddenPrompt').value;
if (secretText.length > 0) {
  const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
  const data = imageData.data;

  const binary = [...unescape(encodeURIComponent(secretText))]
    .map(char => char.charCodeAt().toString(2).padStart(8, '0'))
    .join('') + '00000000'; // add null terminator

  const maxLen = Math.floor(data.length / 4); // One byte per pixel alpha
  if (binary.length > maxLen) {
    alert("Message too long to encode in this image.");
    return;
  }

  for (let i = 0; i < binary.length; i++) {
    const alphaIndex = i * 4 + 3;
    const originalAlpha = data[alphaIndex];
    const bit = binary[i];
    data[alphaIndex] = (originalAlpha & 0b11111110) | parseInt(bit);
  }
  ctx.putImageData(imageData, 0, 0);
}

// Always place image on clipboard.
copyCanvasImageToClipboard(canvas);

});

// Clear button.
document.getElementById('clearButton').addEventListener('click', () => {
  if (originalImageSrc) {
    loadImageFromURL(originalImageSrc);
  } else {
    placeholderText.classList.remove('d-none');
    canvas.classList.add('d-none');
    ctx.clearRect(0, 0, canvas.width, canvas.height);
  }
});

// Drag-and-drop option.
imageFrame.addEventListener('dragover', (event) => {
event.preventDefault();
imageFrame.classList.add('dragover');
});
imageFrame.addEventListener('dragleave', () => {
imageFrame.classList.remove('dragover');
});
imageFrame.addEventListener('drop', (event) => {
event.preventDefault();
imageFrame.classList.remove('dragover');
const file = event.dataTransfer.files[0];
if (file && file.type.startsWith('image/')) {
    loadImageFromFile(file);
}
});

// Ctrl-V option.
document.addEventListener('paste', (event) => {
const items = event.clipboardData.items;
for (let i = 0; i < items.length; i++) {
    if (items[i].type.startsWith('image/')) {
    const blob = items[i].getAsFile();
    loadImageFromBlob(blob);
    break;
    }
}
});

// Load image from a file.
function loadImageFromFile(file) {
const reader = new FileReader();
reader.onload = (e) => {
    loadImageFromURL(e.target.result);
};
reader.readAsDataURL(file);
}

// Load image from a blob.
function loadImageFromBlob(blob) {
const reader = new FileReader();
reader.onload = (e) => {
    loadImageFromURL(e.target.result);
};
reader.readAsDataURL(blob);
}

// Decode the steganographic prompt, if present.
function decodeAlphaMessageFromCanvas() {
  const secretInput = document.getElementById('hiddenPrompt');
  const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
  const data = imageData.data;

  let binary = '';
  let nonOpaqueAlphaFound = false;

  for (let i = 3; i < data.length; i += 4) {
    const alpha = data[i];
    if (alpha !== 255) nonOpaqueAlphaFound = true;
    binary += (alpha & 1).toString(); // LSB
  }

  if (!nonOpaqueAlphaFound) {
    secretInput.placeholder = "E.g. Model, version, date, prompt...";
    return;
  }

  const chars = [];
  for (let i = 0; i < binary.length; i += 8) {
    const byte = binary.slice(i, i + 8);
    if (byte.length < 8) break;
    const code = parseInt(byte, 2);
    if (code === 0) break; // Null terminator
    chars.push(String.fromCharCode(code));
  }

  try {
    const message = chars.join('');
    secretInput.placeholder = message || "(no prompt found, you can add one)";
  } catch (e) {
    secretInput.placeholder = "(error decoding prompt)";
    console.log(e);
  }
}

// Load image and read its C2PA data if present.
function loadImageFromURL(url) {
  const image = new Image();
  image.onload = async () => {

    // 0. Remove any popover.
    popoverContainer.classList.add('d-none');

    // 1. Show canvas and hide placeholder.
    placeholderText.classList.add('d-none');
    canvas.classList.remove('d-none');
    originalImageSrc = url; // Save original

    // 2. Set canvas dimensions and draw image.
    canvas.width = image.width;
    canvas.height = image.height;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(image, 0, 0, canvas.width, canvas.height);

    // 3. Position the cai-popover relative to the image.
    const canvasRect = canvas.getBoundingClientRect();
    const imageFrameRect = imageFrame.getBoundingClientRect();

    // Calculate the top and right offset for the popover relative to the imageFrame.
    // Add some padding (e.g., 10px) from the image edges.
    const popoverTop = canvasRect.top - imageFrameRect.top + 10;
    const popoverRight = imageFrameRect.right - canvasRect.right + 10;
    popoverContainer.style.top = `${popoverTop}px`;
    popoverContainer.style.right = `${popoverRight}px`;

    // Steganographic message.
    decodeAlphaMessageFromCanvas();

    // C2PA metadata, if available.
    if (c2paSdk) {
      try {
        const { manifestStore } = await c2paSdk.read(url);
        popoverContainer.classList.remove('d-none');
        const manifestSummary = getManifestSummaryStore(manifestStore);
        console.log('manifestStore', manifestStore);
        console.log('manifestSummaryStore', manifestSummary);
        document.getElementById('manifest-summary-issuer').innerHTML = manifestStore.activeManifest?.signatureInfo?.issuer || 'N/A';
        let date = manifestStore.activeManifest?.signatureInfo?.time || 'N/A';
        document.getElementById('manifest-summary-date').innerHTML = date.split('T')[0];
        document.getElementById('manifest-summary-title').innerHTML = manifestStore.activeManifest?.title || 'N/A';
        document.getElementById('manifest-summary-recorder').innerHTML = manifestSummary?.recorder || 'N/A';
        document.getElementById('manifest-summary-content-tag').innerHTML = manifestSummary?.contentSummaryTag || 'N/A';
      } catch (err) {
        console.error('Error reading C2PA data from image:', err);
        popoverContainer.classList.add('d-none');
      }
    } else {
      console.warn('C2PA SDK not initialized. Cannot read C2PA data.');
      popoverContainer.classList.add('d-none');
    }
  };
  image.src = url;
}
